### ISSUE TITLE
Adding a net task with the `--dry-run` flag does not work

### ISSUE THREAD

**Issue by SuperJappie08** [VladimirMarkelov/ttdl#70]
Hello,

When using the ttdl tool (Version 3.6.2, I'm on 64-bit, so it should not matter it is not right?) 
I wanted to do the following:
```
 > ttdl a "text +Prj ttttt ttt @Contx due:today" --dry-run
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 58', C:\Users\USERa\.cargo\registry\src\github.com-1ecc6299db9ec823\ttdl-3.6.2\src\fmt.rs:1329:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After some more testing, it turned out that the `--dry-run` flag does not work on add command.
## Simplest example:
```
> ttdl a "test" --dry-run
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 58', C:\Users\USERa\.cargo\registry\src\github.com-1ecc6299db9ec823\ttdl-3.6.2\src\fmt.rs:1329:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Extra Information:
- OS: 64-bit Windows 10
- Shell: PowerShell
- Installed via: cargo
- Version of ttdl: 3.6.2

**Comment by VladimirMarkelov** [comment]
Thank you for the report! I'll fix it as soon as possible.
